[theme]
base = "dark"
primaryColor="#FEBE8C" 			# theme
secondaryBackgroundColor="#FFFBC1" 		# side bar
backgroundColor ="#B6E2A1"
font ="sans serif"
textColor ="#393E46"
# Background color for the main content area.
# backgroundColor =

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor =

# Color used for almost all text.
# textColor =

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
